"""
IA Factory Operator - Internal State Classes
State management for video processing pipeline
"""

from enum import Enum
from typing import List, Optional, Dict, Any
from datetime import datetime
from dataclasses import dataclass, field
from pydantic import BaseModel


# =============================================================================
# SCENE ANALYSIS
# =============================================================================

class SceneType(str, Enum):
    """Types of detected scenes"""
    talking_head = "talking_head"
    product_shot = "product_shot"
    b_roll = "b_roll"
    text_overlay = "text_overlay"
    transition = "transition"
    logo = "logo"
    action = "action"
    static = "static"
    unknown = "unknown"


class EmotionalTone(str, Enum):
    """Emotional tone of a scene"""
    neutral = "neutral"
    excited = "excited"
    professional = "professional"
    warm = "warm"
    urgent = "urgent"
    calm = "calm"
    dramatic = "dramatic"


@dataclass
class SceneSegment:
    """A detected scene segment in the video"""
    
    start_time: float  # seconds
    end_time: float  # seconds
    duration: float  # seconds
    
    scene_type: SceneType = SceneType.unknown
    confidence: float = 0.0
    
    # Visual analysis
    dominant_colors: List[str] = field(default_factory=list)
    brightness: float = 0.5  # 0-1
    motion_score: float = 0.0  # 0-1
    
    # Audio analysis
    has_speech: bool = False
    speech_confidence: float = 0.0
    audio_level: float = 0.0  # dB normalized
    
    # Content
    transcript: str = ""
    detected_objects: List[str] = field(default_factory=list)
    faces_detected: int = 0
    
    # Quality scores
    quality_score: float = 0.5  # 0-1
    engagement_score: float = 0.5  # 0-1 (predicted)
    
    # For edit decisions
    keep: bool = True
    priority: int = 5  # 1-10, higher = more important
    
    def __post_init__(self):
        self.duration = self.end_time - self.start_time


@dataclass
class VideoAnalysis:
    """Complete analysis of a source video"""
    
    # Basic info
    file_path: str
    duration: float
    width: int
    height: int
    fps: float
    codec: str
    bitrate: int
    file_size: int
    
    # Detected content
    scenes: List[SceneSegment] = field(default_factory=list)
    total_scenes: int = 0
    
    # Audio analysis
    has_audio: bool = True
    audio_channels: int = 2
    audio_sample_rate: int = 44100
    
    # Transcript
    full_transcript: str = ""
    transcript_segments: List[Dict[str, Any]] = field(default_factory=list)
    detected_language: str = "fr"
    
    # Quality assessment
    overall_quality: float = 0.5
    audio_quality: float = 0.5
    visual_quality: float = 0.5
    
    # Content understanding
    summary: str = ""
    keywords: List[str] = field(default_factory=list)
    emotional_tone: EmotionalTone = EmotionalTone.neutral
    
    # Timestamp
    analyzed_at: datetime = field(default_factory=datetime.utcnow)


# =============================================================================
# EDIT PLAN
# =============================================================================

class EditActionType(str, Enum):
    """Types of editing actions"""
    trim = "trim"
    cut = "cut"
    speed_change = "speed_change"
    transition = "transition"
    text_overlay = "text_overlay"
    caption = "caption"
    music_overlay = "music_overlay"
    color_grade = "color_grade"
    crop_resize = "crop_resize"
    zoom = "zoom"
    pan = "pan"
    fade_in = "fade_in"
    fade_out = "fade_out"
    voiceover = "voiceover"


class TransitionType(str, Enum):
    """Types of transitions"""
    cut = "cut"
    dissolve = "dissolve"
    fade = "fade"
    swipe_left = "swipe_left"
    swipe_right = "swipe_right"
    swipe_up = "swipe_up"
    swipe_down = "swipe_down"
    zoom_in = "zoom_in"
    zoom_out = "zoom_out"


@dataclass
class EditAction:
    """A single editing action in the plan"""
    
    action_type: EditActionType
    start_time: float
    end_time: float
    
    # Action-specific parameters
    params: Dict[str, Any] = field(default_factory=dict)
    
    # Execution order
    order: int = 0
    layer: int = 0  # 0 = base video, 1+ = overlays
    
    # For tracking
    applied: bool = False
    error: Optional[str] = None


@dataclass
class EditPlan:
    """Complete edit plan generated by LLM planner"""
    
    # Plan identification
    plan_id: str = ""
    created_at: datetime = field(default_factory=datetime.utcnow)
    
    # Target specs
    target_duration: float = 15.0
    target_width: int = 1080
    target_height: int = 1920
    target_fps: float = 30.0
    
    # Source selection
    scenes_to_use: List[int] = field(default_factory=list)  # indices
    
    # Edit actions
    actions: List[EditAction] = field(default_factory=list)
    
    # Captions
    caption_segments: List[Dict[str, Any]] = field(default_factory=list)
    caption_style: Dict[str, Any] = field(default_factory=dict)
    
    # Music/Audio
    music_track: Optional[str] = None
    music_volume: float = 0.3  # 0-1
    voice_volume: float = 1.0  # 0-1
    
    # Style settings
    color_grade_preset: Optional[str] = None
    
    # LLM reasoning
    reasoning: str = ""
    confidence: float = 0.0


# =============================================================================
# VIDEO EDITOR STATE
# =============================================================================

@dataclass
class VideoEditorState:
    """
    Main state object that flows through the pipeline.
    Contains all information needed at each stage.
    """
    
    # Job identification
    job_id: str
    user_id: Optional[str] = None
    
    # Input request (from API)
    source_video_url: str = ""
    template: str = "algerian_minimal"
    target_duration: int = 15
    platforms: List[str] = field(default_factory=list)
    style: str = "default"
    language: str = "fr"
    add_captions: bool = True
    add_music: bool = False
    voiceover_text: Optional[str] = None
    webhook_url: Optional[str] = None
    
    # Processing state
    status: str = "pending"
    progress: int = 0
    current_stage: str = ""
    
    # File paths
    source_video_path: Optional[str] = None
    work_dir: Optional[str] = None
    
    # Pipeline results
    analysis: Optional[VideoAnalysis] = None
    edit_plan: Optional[EditPlan] = None
    
    # Outputs
    output_files: Dict[str, str] = field(default_factory=dict)  # platform -> path
    output_urls: Dict[str, str] = field(default_factory=dict)  # platform -> url
    thumbnail_urls: Dict[str, str] = field(default_factory=dict)
    
    # Timing
    created_at: datetime = field(default_factory=datetime.utcnow)
    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None
    
    # Logging
    logs: List[str] = field(default_factory=list)
    error: Optional[str] = None
    
    # Stats
    processing_time: Optional[float] = None
    
    def add_log(self, message: str):
        """Add a log message with timestamp"""
        timestamp = datetime.utcnow().strftime("%H:%M:%S")
        self.logs.append(f"[{timestamp}] {message}")
    
    def set_status(self, status: str, progress: int = None, stage: str = None):
        """Update status and progress"""
        self.status = status
        if progress is not None:
            self.progress = progress
        if stage is not None:
            self.current_stage = stage
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for serialization"""
        return {
            "job_id": self.job_id,
            "user_id": self.user_id,
            "status": self.status,
            "progress": self.progress,
            "current_stage": self.current_stage,
            "source_video_url": self.source_video_url,
            "template": self.template,
            "target_duration": self.target_duration,
            "platforms": self.platforms,
            "output_urls": self.output_urls,
            "thumbnail_urls": self.thumbnail_urls,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "completed_at": self.completed_at.isoformat() if self.completed_at else None,
            "logs": self.logs,
            "error": self.error,
        }
    
    @classmethod
    def from_request(cls, job_id: str, request: "VideoEditRequest") -> "VideoEditorState":
        """Create state from API request"""
        return cls(
            job_id=job_id,
            source_video_url=str(request.source_video_url),
            template=request.template.value if hasattr(request.template, 'value') else request.template,
            target_duration=request.target_duration,
            platforms=[p.value if hasattr(p, 'value') else p for p in request.platforms],
            style=request.style.value if hasattr(request.style, 'value') else request.style,
            language=request.language.value if hasattr(request.language, 'value') else request.language,
            add_captions=request.add_captions,
            add_music=request.add_music,
            voiceover_text=request.voiceover_text,
            webhook_url=str(request.webhook_url) if request.webhook_url else None,
        )


# =============================================================================
# PLATFORM SPECS
# =============================================================================

PLATFORM_SPECS = {
    "instagram_reels": {
        "width": 1080,
        "height": 1920,
        "aspect_ratio": "9:16",
        "max_duration": 90,
        "recommended_duration": 15,
        "fps": 30,
    },
    "tiktok": {
        "width": 1080,
        "height": 1920,
        "aspect_ratio": "9:16",
        "max_duration": 180,
        "recommended_duration": 30,
        "fps": 30,
    },
    "youtube_shorts": {
        "width": 1080,
        "height": 1920,
        "aspect_ratio": "9:16",
        "max_duration": 60,
        "recommended_duration": 30,
        "fps": 30,
    },
    "square": {
        "width": 1080,
        "height": 1080,
        "aspect_ratio": "1:1",
        "max_duration": 60,
        "recommended_duration": 15,
        "fps": 30,
    },
}


# =============================================================================
# TEMPLATE DEFINITIONS
# =============================================================================

TEMPLATE_CONFIGS = {
    "product_demo": {
        "name_fr": "Démo Produit",
        "name_ar": "عرض المنتج",
        "name_en": "Product Demo",
        "prefer_scenes": ["product_shot", "action"],
        "caption_position": "bottom",
        "music_style": "upbeat",
        "color_grade": "vibrant",
    },
    "talking_head": {
        "name_fr": "Face Caméra",
        "name_ar": "مقابلة",
        "name_en": "Talking Head",
        "prefer_scenes": ["talking_head"],
        "caption_position": "bottom",
        "music_style": None,
        "color_grade": "natural",
    },
    "food_promo": {
        "name_fr": "Promo Restaurant",
        "name_ar": "ترويج مطعم",
        "name_en": "Food Promo",
        "prefer_scenes": ["product_shot", "action"],
        "caption_position": "bottom",
        "music_style": "warm",
        "color_grade": "warm",
    },
    "real_estate": {
        "name_fr": "Immobilier",
        "name_ar": "عقارات",
        "name_en": "Real Estate",
        "prefer_scenes": ["b_roll", "static"],
        "caption_position": "bottom",
        "music_style": "elegant",
        "color_grade": "bright",
    },
    "algerian_minimal": {
        "name_fr": "Minimal Algérien",
        "name_ar": "بسيط جزائري",
        "name_en": "Algerian Minimal",
        "prefer_scenes": ["talking_head", "product_shot"],
        "caption_position": "bottom",
        "music_style": "traditional_modern",
        "color_grade": "natural",
    },
    "energetic": {
        "name_fr": "Énergétique",
        "name_ar": "نشيط",
        "name_en": "Energetic",
        "prefer_scenes": ["action", "b_roll"],
        "caption_position": "center",
        "music_style": "energetic",
        "color_grade": "vibrant",
    },
    "cinematic": {
        "name_fr": "Cinématique",
        "name_ar": "سينمائي",
        "name_en": "Cinematic",
        "prefer_scenes": ["b_roll", "action"],
        "caption_position": "bottom",
        "music_style": "epic",
        "color_grade": "cinematic",
    },
}
